#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include <cstdlib>

int main() {
	std::string targetCard;
	std::string nvidKey = "YOUR API KEY HERE";
	std::string instrctIn = "INstructions.json";
	std::string respOut = "response.json";

	
	std::ofstream instructIons(instrctIn);
	instructIons << "{\n";
	instructIons << "  \"model\": \"google/gemma-4-31b-it\",\n";
	instructIons << "  \"messages\": [\n";
	instructIons << "    {\"role\": \"user\", \"content\": \"Write exactly one funny short sentence of lore for a robot named Gemi, specifically for SillyTavenAI.\"}\n";
	instructIons << "  ]\n";
	instructIons << "}\n";

	if (instructIons.is_open()) {
		std::cout << "success!";
	}
	else {
	    std::cout << "failed! is something wrong?";
	}

	instructIons.close();

	std::string command = "curl -s -X POST \"https://integrate.api.nvidia.com/v1/chat/completions\" ";
	command += "-H \"Authorization: Bearer " + nvidKey + "\" ";
	command += "-H \"Content-Type: application/json\" ";
	command += "-d @" + instrctIn + " ";
	command += "> " + respOut;


	system(command.c_str());

	std::ifstream scanner(respOut);
	std::string basebucket;

    if (std::getline(scanner, basebucket)) {
		size_t startPos = basebucket.find("\"content\":\"");

		if (startPos != std::string::npos) {

		    startPos += 11;

			size_t endPos = basebucket.find("\"", startPos);

			if (endPos != std::string::npos) {
				size_t inLength = endPos - startPos;
				std::string extractedKey = basebucket.substr(startPos, inLength);
				std::cout << extractedKey;
					
				std::ofstream finP("finlore.json");

				finP << "{\n";
				finP << "  \"name\": \"Gemi's Auto-Lore\",\n";
				finP << "  \"description\": \"Generated by Nvidia API via C++\",\n";
				finP << "  \"scan_depth\": 2,\n";
				finP << "  \"token_budget\": 500,\n";
				finP << "  \"recursive_scanning\": false,\n";
				finP << "  \"extensions\": {},\n";
				finP << "  \"entries\": {\n";
				finP << "    \"0\": {\n";
				finP << "      \"uid\": 0,\n";
				finP << "      \"key\": [\"gemi\", \"robot\"],\n";
				finP << "      \"keysecondary\": [],\n";
				finP << "      \"comment\": \"AI Generated Entry\",\n";
				finP << "      \"content\": \"" << extractedKey << "\",\n";
				finP << "      \"constant\": false,\n";
				finP << "      \"selective\": false,\n";
				finP << "      \"order\": 100,\n";
				finP << "      \"position\": 1,\n";
				finP << "      \"disable\": false\n";
				finP << "    }\n";
				finP << "  }\n";
				finP << "}\n";

				finP.close();

				std::cout << "\nSUCCESS: finlore.json has been created and formatted for SillyTavern!\n";

		    }
       	}
    }

    scanner.close();

	return 0;

}