#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include <cstdlib>

int main(int argc, char* argv[]) {
	std::ifstream payloadFile("payload.txt");
	if (!payloadFile.is_open()) {
		std::cout << "Error: Could not find payload.txt!" << std::endl;
		return 1;
	}
	std::string charName, charPers, charDesc, charNotes, charMes, charScen;
	std::getline(payloadFile, charName);
	std::getline(payloadFile, charPers);
	std::getline(payloadFile, charDesc);
	std::getline(payloadFile, charNotes);
	std::getline(payloadFile, charMes);
	std::getline(payloadFile, charScen);
	payloadFile.close();

	std::string targetCard;
	std::string nvidKey = "your_api_here";
	std::string instrctIn = "INstructions.json";
	std::string respOut = "response.json";
	std::string dynamicPrompt = "You are an expert world-builder for a roleplay game. The character's name is " + charName + ". Their personality is " + charPers + ". The overarching scenario is " + charScen + ". Based on their core description: " + charDesc + ", and the creator's secret world-building notes: " + charNotes + ", read their first message to get the exact tone and vibe of the universe: " + charMes + ". Now, generate 5 rich, highly detailed lorebook entries about locations, items, or rules associated with this exact universe. Keep it under 60 words per entry and do not write any dialogue.";
	
	std::ofstream instructIons(instrctIn);
	instructIons << "{\n";
	instructIons << "  \"model\": \"google/gemma-4-31b-it\",\n";
	instructIons << "  \"messages\": [\n";
	instructIons << "    {\"role\": \"user\", \"content\": \"" << dynamicPrompt << "\"}\n";
	instructIons << "  ]\n";
	instructIons << "}\n";

	if (instructIons.is_open()) {
		std::cout << "success!";
	}
	else {
	    std::cout << "failed! is something wrong?";
	}

	instructIons.close();

	std::string command = "curl -s -X POST \"https://integrate.api.nvidia.com/v1/chat/completions\" ";
	command += "-H \"Authorization: Bearer " + nvidKey + "\" ";
	command += "-H \"Content-Type: application/json\" ";
	command += "-d @" + instrctIn + " ";
	command += "> " + respOut;


	system(command.c_str());



	std::ifstream scanner(respOut);
	std::string basebucket;
	std::string tempLine;

	while (std::getline(scanner, tempLine)) {
		basebucket += tempLine;
	}

	size_t startPos = basebucket.find("\"content\":\"");

	if (startPos != std::string::npos) {
		startPos += 11; 

		size_t endPos = basebucket.find("\"},", startPos);

		if (endPos != std::string::npos) {
			size_t inLength = endPos - startPos;
			std::string extractedKey = basebucket.substr(startPos, inLength);
			std::cout << "\nEXTRACTED LORE:\n" << extractedKey << "\n";

			std::ofstream finP("finlore.json");

			finP << "{\n";
		
			finP << "  \"name\": \"" << charName << "'s Auto-Lore\",\n";
			finP << "  \"description\": \"Generated by Nvidia API via C++\",\n";
			finP << "  \"scan_depth\": 2,\n";
			finP << "  \"token_budget\": 500,\n";
			finP << "  \"recursive_scanning\": false,\n";
			finP << "  \"extensions\": {},\n";
			finP << "  \"entries\": {\n";
			finP << "    \"0\": {\n";
			finP << "      \"uid\": 0,\n";
			finP << "      \"key\": [\"" << charName << "\"],\n";
			finP << "      \"keysecondary\": [],\n";
			finP << "      \"comment\": \"AI Generated Entry\",\n";
			finP << "      \"content\": \"" << extractedKey << "\",\n";
			finP << "      \"constant\": false,\n";
			finP << "      \"selective\": false,\n";
			finP << "      \"order\": 100,\n";
			finP << "      \"position\": 1,\n";
			finP << "      \"disable\": false\n";
			finP << "    }\n";
			finP << "  }\n";
			finP << "}\n";

			finP.close();

			std::cout << "\nSUCCESS: finlore.json has been created and formatted for SillyTavern!\n";
		}
	}
	else {
		std::cout << "\nERROR: Could not find the content block in response.json!\n";
	}

	scanner.close();

	return 0;
}